### ISSUE TITLE
Tracking past performance across all attribute values (rather than for each individual attribute value)

### ISSUE THREAD

**Issue by cmaclell** [cmaclell/concept_formation#11]

**Comment by eharpste** [comment]
Would this differ greatly from averaging past performance across all attributes every time the value is used? Like is done in the output_json pruning.

**Comment by cmaclell** [comment]
Didn't we remove past_performance tracking? Can I clear this enhancement?

**Comment by eharpste** [comment]
We did remove past performance tracking, though maybe its still in a branch? I'll kill the issue anyway.
