### ISSUE TITLE
Heuristic in structure mapper not as good as expected

### ISSUE THREAD

**Issue by cmaclell** [cmaclell/concept_formation#15]
It would seem that the heuristic used by the structure mapper does not ensure that the best match is found when beam width is 1 and there are only components (no other relations or subcomponents).

**Comment by eharpste** [comment]
We basically we can't guarantee the best match being found but that the new structure mapper uses Hungarian algorithm and refines it with local search for relations and that is sufficient for now. Essentially any situation in where you can find the optimal solution in a feasible time frame the local search will usually find it anyway.
