### ISSUE TITLE
Make structure mapping faster

### ISSUE THREAD

**Issue by cmaclell** [cmaclell/concept_formation#16]
The code in concept_formation.structure_mapper.compute_rewards should probably be optimized so that the calculation is faster. 

Also, look at the use of the rewards.. maybe we can do some kind of dynamic programming to cache previous parts of the search.

**Comment by cmaclell** [comment]
Currently, we used a form of graph search where we progressively build up the structure mapping in a greedy way. I'm currently exploring an alternative that enumerates a full mapping and then progressively improves it by flipping matches using hill climbing or simulated annealing. 

Results with n-queens and similar problems suggests that this later, local-search based, approach is superior often yielding search time that is invariant of problem size (i.e., constant).

**Comment by eharpste** [comment]
This issue is addressed by the most recent pull request #22 so I am going to close it
