### ISSUE TITLE
Is attr_val_guess_gain properly handling None probabilities?

### ISSUE THREAD

**Issue by cmaclell** [cmaclell/concept_formation#31]
I'm not sure, I suspect what we have works, but isn't 100% correct.

**Comment by eharpste** [comment]
@cmaclell thinks this one might be solved but double check.

**Comment by cmaclell** [comment]
I believe we're good going to close this issue. I can't remember the exact changes made here, but it loos like we no longer use attr_value_guess_gain. Now we just copy the node, add the instance, then compute the expected correct guesses. My guess is that we did this to avoid exactly this issue of missing values being handled properly.

Also, based on this discussion I added #78 to explore multiple ways to handle missing values.
